{ config, pkgs, ... }: {

  xdg.configFile."hypr/hyprland.conf".text = ''
# AUTOGENERATED HYPRLAND CONFIG

# ========================
# MONITORS
# ========================
monitor=,preferred,auto,auto

# ========================
# MY PROGRAMS
# ========================
$terminal = alacritty
$fileManager = thunar
$menu = fuzzel

xwayland{
    force_zero_scaling=true
}

# ========================
# KEYBINDS
# ========================
$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, thunar
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, fuzzel
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod SHIFT, F, fullscreen, 1

# ========================
# WINDOWS
# ========================
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(eeccccff) rgba(ee99aaff) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
    force_split_new = true
}

# ========================
# MOUSE
# ========================
mouse {
    accel_profile = adaptive
}

# ========================
# INPUT
# ========================
input {
    kb_layout = cn
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
    }
}

# ========================
# AUTOSTART
# ========================
exec-once = waybar
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY:XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
'';

  home.sessionVariables = {
    HYPRLAND_INSTANCE_SIGNATURE = "Hyprland";
  };
}